### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by shutter-cp** [Germey/ProxyPool#27]
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from proxypool.schedule import Schedule
  File "E:\soft\Python\untitled\2\ProxyPool\proxypool\schedule.py", line 11, in <module>
    from proxypool.getter import FreeProxyGetter
  File "E:\soft\Python\untitled\2\ProxyPool\proxypool\getter.py", line 1, in <module>
    from .utils import get_page
  File "E:\soft\Python\untitled\2\ProxyPool\proxypool\utils.py", line 5, in <module>
    from fake_useragent import UserAgent,FakeUserAgentError
ModuleNotFoundError: No module named 'fake_useragent'

**Comment by zd398900463** [comment]
cmd：pip install fake_useragent
