### ISSUE TITLE
Could you help me with this?

### ISSUE THREAD

**Issue by BingoWon** [Germey/ProxyPool#31]
Every time I run run.py, the following shows up after a few seconds and the program just stops.

Process Process-2:
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\Program Files (x86)\Python\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\LEARNING\ProxyPool-master\proxypool\scheduler.py", line 28, in schedule_getter
    getter.run()
  File "D:\LEARNING\ProxyPool-master\proxypool\getter.py", line 30, in run
    self.redis.add(proxy)
  File "D:\LEARNING\ProxyPool-master\proxypool\db.py", line 30, in add
    return self.db.zadd(REDIS_KEY, score, proxy)
  File "D:\Program Files (x86)\Python\Python36\lib\site-packages\redis\client.py", line 2263, in zadd
    for pair in iteritems(mapping):
  File "D:\Program Files (x86)\Python\Python36\lib\site-packages\redis\_compat.py", line 123, in iteritems
    return iter(x.items())
AttributeError: 'int' object has no attribute 'items'

**Comment by aefuimn** [comment]
Your moudle of redis version should be lower than 3.0,  if you use python3 , you can use 2.10.6
