### ISSUE TITLE
首次运行报错AttributeError: 'int' object has no attribute 'items'

### ISSUE THREAD

**Issue by Doyus** [Germey/ProxyPool#33]
正在抓取 http://www.ip3366.net/?stype=1&page=3
抓取成功 http://www.ip3366.net/?stype=1&page=3 200
成功获取到代理 221.126.249.99:8080
成功获取到代理 115.225.127.235:9999
成功获取到代理 182.146.253.173:8118
成功获取到代理 182.88.14.46:8123
成功获取到代理 103.79.228.230:43138
成功获取到代理 220.175.182.121:9999
成功获取到代理 113.13.160.105:9999
成功获取到代理 110.52.235.160:9999
成功获取到代理 115.46.96.169:8123
成功获取到代理 121.31.156.243:8123
Traceback (most recent call last):
  File "D:\anacoda\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\anacoda\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "F:\python\ProxyPool-master\ProxyPool-master\proxypool\scheduler.py", line 28, in schedule_getter
    getter.run()
  File "F:\python\ProxyPool-master\ProxyPool-master\proxypool\getter.py", line 30, in run
    self.redis.add(proxy)
  File "F:\python\ProxyPool-master\ProxyPool-master\proxypool\db.py", line 30, in add
    return self.db.zadd(REDIS_KEY, score, proxy)
  File "D:\anacoda\lib\site-packages\redis\client.py", line 2263, in zadd
    for pair in iteritems(mapping):
  File "D:\anacoda\lib\site-packages\redis\_compat.py", line 123, in iteritems
    return iter(x.items())

**Comment by Havenwalk** [comment]
同样的问题

**Comment by Havenwalk** [comment]
> 同样的问题


代理池开始运行
 * Serving Flask app "proxypool.api" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5555/ (Press CTRL+C to quit)
开始抓取代理
获取器开始执行
Crawling http://www.66ip.cn/1.html
正在抓取 http://www.66ip.cn/1.html
抓取成功 http://www.66ip.cn/1.html 521
Crawling http://www.66ip.cn/2.html
正在抓取 http://www.66ip.cn/2.html
抓取成功 http://www.66ip.cn/2.html 521
Crawling http://www.66ip.cn/3.html
正在抓取 http://www.66ip.cn/3.html
抓取成功 http://www.66ip.cn/3.html 521
Crawling http://www.66ip.cn/4.html
正在抓取 http://www.66ip.cn/4.html
抓取成功 http://www.66ip.cn/4.html 521
Process Process-2:
正在抓取 http://www.ip3366.net/?stype=1&page=1
抓取失败 http://www.ip3366.net/?stype=1&page=1
正在抓取 http://www.ip3366.net/?stype=1&page=2
抓取成功 http://www.ip3366.net/?stype=1&page=2 200
成功获取到代理 175.0.121.153:8060
成功获取到代理 116.226.158.217:8060
成功获取到代理 123.115.128.79:8060
成功获取到代理 119.190.151.19:8060
成功获取到代理 114.99.255.209:8118
成功获取到代理 222.182.121.55:8118
成功获取到代理 180.175.2.31:8060
成功获取到代理 122.235.247.219:8118
成功获取到代理 103.211.49.209:45789
成功获取到代理 104.152.248.130:53281
正在抓取 http://www.ip3366.net/?stype=1&page=3
抓取成功 http://www.ip3366.net/?stype=1&page=3 200
成功获取到代理 104.152.248.130:53281
成功获取到代理 115.46.103.194:8123
成功获取到代理 47.90.203.47:3128
成功获取到代理 180.122.149.63:9999
成功获取到代理 123.114.203.77:8118
成功获取到代理 27.203.160.37:8060
成功获取到代理 119.180.140.207:8060
成功获取到代理 113.213.76.132:80
成功获取到代理 119.180.169.212:8060
成功获取到代理 111.124.194.124:8118
Traceback (most recent call last):
  File "C:\anacoda\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\anacoda\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\userq\PycharmProjects\webspiderproxy\proxypool\scheduler.py", line 28, in schedule_getter
    getter.run()
  File "C:\Users\user\PycharmProjects\webspiderproxy\proxypool\getter.py", line 30, in run
    self.redis.add(proxy)
  File "C:\Users\user\PycharmProjects\webspiderproxy\proxypool\db.py", line 30, in add
    return self.db.zadd(REDIS_KEY, score, proxy)
  File "C:\anacoda\lib\site-packages\redis\client.py", line 2320, in zadd
    for pair in iteritems(mapping):
  File "C:\anacoda\lib\site-packages\redis\_compat.py", line 122, in iteritems
    return iter(x.items())
AttributeError: 'int' object has no attribute 'items'

**Comment by Scrat250** [comment]
> > 同样的问题
> 
> 代理池开始运行
> 
> * Serving Flask app "proxypool.api" (lazy loading)
> * Environment: production
>   WARNING: Do not use the development server in a production environment.
>   Use a production WSGI server instead.
> * Debug mode: off
> * Running on http://0.0.0.0:5555/ (Press CTRL+C to quit)
>   开始抓取代理
>   获取器开始执行
>   Crawling http://www.66ip.cn/1.html
>   正在抓取 http://www.66ip.cn/1.html
>   抓取成功 http://www.66ip.cn/1.html 521
>   Crawling http://www.66ip.cn/2.html
>   正在抓取 http://www.66ip.cn/2.html
>   抓取成功 http://www.66ip.cn/2.html 521
>   Crawling http://www.66ip.cn/3.html
>   正在抓取 http://www.66ip.cn/3.html
>   抓取成功 http://www.66ip.cn/3.html 521
>   Crawling http://www.66ip.cn/4.html
>   正在抓取 http://www.66ip.cn/4.html
>   抓取成功 http://www.66ip.cn/4.html 521
>   Process Process-2:
>   正在抓取 http://www.ip3366.net/?stype=1&page=1
>   抓取失败 http://www.ip3366.net/?stype=1&page=1
>   正在抓取 http://www.ip3366.net/?stype=1&page=2
>   抓取成功 http://www.ip3366.net/?stype=1&page=2 200
>   成功获取到代理 175.0.121.153:8060
>   成功获取到代理 116.226.158.217:8060
>   成功获取到代理 123.115.128.79:8060
>   成功获取到代理 119.190.151.19:8060
>   成功获取到代理 114.99.255.209:8118
>   成功获取到代理 222.182.121.55:8118
>   成功获取到代理 180.175.2.31:8060
>   成功获取到代理 122.235.247.219:8118
>   成功获取到代理 103.211.49.209:45789
>   成功获取到代理 104.152.248.130:53281
>   正在抓取 http://www.ip3366.net/?stype=1&page=3
>   抓取成功 http://www.ip3366.net/?stype=1&page=3 200
>   成功获取到代理 104.152.248.130:53281
>   成功获取到代理 115.46.103.194:8123
>   成功获取到代理 47.90.203.47:3128
>   成功获取到代理 180.122.149.63:9999
>   成功获取到代理 123.114.203.77:8118
>   成功获取到代理 27.203.160.37:8060
>   成功获取到代理 119.180.140.207:8060
>   成功获取到代理 113.213.76.132:80
>   成功获取到代理 119.180.169.212:8060
>   成功获取到代理 111.124.194.124:8118
>   Traceback (most recent call last):
>   File "C:\anacoda\lib\multiprocessing\process.py", line 297, in _bootstrap
>   self.run()
>   File "C:\anacoda\lib\multiprocessing\process.py", line 99, in run
>   self._target(*self._args, **self._kwargs)
>   File "C:\Users\userq\PycharmProjects\webspiderproxy\proxypool\scheduler.py", line 28, in schedule_getter
>   getter.run()
>   File "C:\Users\user\PycharmProjects\webspiderproxy\proxypool\getter.py", line 30, in run
>   self.redis.add(proxy)
>   File "C:\Users\user\PycharmProjects\webspiderproxy\proxypool\db.py", line 30, in add
>   return self.db.zadd(REDIS_KEY, score, proxy)
>   File "C:\anacoda\lib\site-packages\redis\client.py", line 2320, in zadd
>   for pair in iteritems(mapping):
>   File "C:\anacoda\lib\site-packages\redis_compat.py", line 122, in iteritems
>   return iter(x.items())
>   AttributeError: 'int' object has no attribute 'items'

试试：pip install redis==2.10.6

**Comment by sleepray** [comment]
该怎么改？

**Comment by mirui-bai** [comment]
好像可行
pip install redis==2.10.6

**Comment by mirui-bai** [comment]
可以的

**Comment by liushuaidi** [comment]
pip install redis==2.10.6  可行！！

**Comment by zyyoo** [comment]
pip install redis == 2.10.6可行!!  + 1

**Comment by 708DaLao** [comment]
pip install redis == 2.10.6可行!! + 1
